# Generated by Django 6.0.2 on 2026-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Events last updated at'),
        ),
    ]
