# Generated by Django 6.0.2 on 2026-03-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_events_last_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strike_count',
            field=models.IntegerField(default=0, verbose_name='Strike count'),
        ),
    ]
