# Generated by Django 6.0.2 on 2026-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_strike_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='strike_count',
        ),
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.IntegerField(default=0, verbose_name='Streak count'),
        ),
    ]
