# Generated by Django 6.0.2 on 2026-03-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_strike_count_user_streak_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events_last_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak_count',
        ),
    ]
