# Generated by Django 6.0.2 on 2026-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_events_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.IntegerField(default=0, verbose_name='Streak count'),
        ),
    ]
