# Generated by Django 6.0.2 on 2026-03-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_streak_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='streak_count',
        ),
    ]
