# Generated by Django 6.0.2 on 2026-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.IntegerField(default=0, verbose_name='Streak count'),
        ),
    ]
