# Generated by Django 6.0.2 on 2026-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_leaderboard',
            field=models.BooleanField(default=True, verbose_name='In leaderboard'),
        ),
    ]
