# Generated by Django 6.0.2 on 2026-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_in_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='in_leaderboard',
            field=models.BooleanField(db_index=True, default=True, verbose_name='In leaderboard'),
        ),
    ]
