# Generated by Django 6.0.2 on 2026-02-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotional_state', models.CharField(choices=[('bad', 'Bad'), ('neutral', 'Neutral'), ('good', 'Good')], max_length=10, verbose_name='Emotional state')),
                ('data', models.JSONField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
