# Generated by Django 6.0.2 on 2026-03-13 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_make_event_user_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='data',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_data',
            field=models.JSONField(default={}, verbose_name='Event data'),
            preserve_default=False,
        ),
    ]
