# Generated by Django 6.0.2 on 2026-03-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_unique_user_date_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_streak',
            field=models.BooleanField(default=False, verbose_name='In streak'),
        ),
    ]
